New Resource: aws s3 bucket
chef/inspec-aws pull request #159
Opened 2017-12-26 16:56 UTC by dromazmj

* Adds functionality for checking the permissions of specific users in a buckets
    - can check the owner, authorized users, everyone and log group
* Adds functionality for checking if the bucket has any public files

2017-12-26 21:31 UTC, aaronlippold commented on docs/resources/aws_s3_bucket.md
> +      its('permissions_owner') { should cmp ['FULL_CONTROL'] }
Left over from last push

2017-12-26 21:31 UTC, aaronlippold commented on docs/resources/aws_s3_bucket.md
> +
Should we have a test in here for the region?

2018-01-05 02:08 UTC, clintoncwolfe requested changes
My overall impression is that is has a lot of good work in it.  This is really two PRs: create the resource, and then add ACL-based access analysis.  I'd want to see something in the docs about limitations (for example, scalability issues on object ACLs, and no bucket profile analysis).  NOT asking for those to be added to this PR - smaller, more focused PRs are more desirable.

I haven't run the tests yet on this; once the fixes are in, I'll move on to that.  Great contribution, and thanks @dromazmj !

2018-01-05 02:08 UTC, clintoncwolfe commented on test/unit/resources/aws_s3_bucket_test.rb
> +  # Testing Propertys of a public bucket
Properties, not Propertys :)

2018-01-05 03:08 UTC, aaronlippold commented on docs/resources/aws_s3_bucket.md
> +### permissions (Hash)
I agree for ongoing PRs ... are these ok for the first round or do you really want to split out these into two PRs each?

2018-01-05 03:08 UTC, aaronlippold commented on docs/resources/aws_s3_bucket.md
> +      # Check what extension categories we have
we do that below correct?

2018-01-05 03:08 UTC, aaronlippold commented on docs/resources/aws_s3_bucket.md
> +      # Check what extension categories we have
Do you want us to remove that example? I think @dromazmj was just trying to show you could look at the whole set of permissions.

2018-01-05 03:15 UTC, clintoncwolfe commented on docs/resources/aws_s3_bucket.md
> +### permissions (Hash)
I'm OK either way.  I'm just trying to let you know what affects the velocity of the review process.

2018-01-05 03:19 UTC, clintoncwolfe commented on docs/resources/aws_s3_bucket.md
> +      # Check what extension categories we have
I'm saying the first set of examples are potentially confusing, while the remainder are excellent.  So like this:
```
describe aws_s3_bucket('test_bucket') do
    # Check examples of 'owner'
    its('permissions.owner') { should be_in ['FULL_CONTROL'] }

    # Check examples of 'authUsers'
    its('permissions.authUsers') { should be_in ['READ'] }

    # Check examples of 'everyone'
    its('permissions.everyone') { should be_in [] }

    # Check examples of the 'logGroup'
   its('permissions.logGroup') { should be_in ['WRITE'] }
end
```

Might be a better (clearer) matcher than `be_in` (perhaps `cmp`), the main point is the latter examples are good.

2018-01-05 03:21 UTC, clintoncwolfe commented on docs/resources/aws_s3_bucket.md
> +The `objects` hash property is used for testing the objects in a bucket.
We generally lean toward fluent reading - we assume the profile should be understandable by an auditor, so `public_objects` is better to me than `objects.public`.

2018-01-05 03:22 UTC, clintoncwolfe commented on docs/resources/aws_s3_bucket.md
> +The `have_public_files` matcher tests if the S3 Bucket has any files that are open to the public. Returns a true if one or more objects in the bucket are public.  If no objects are public returns fal
Yes, I absolutely agree we should document what `have_public_objects` means, from a technical perspective.

2018-01-05 03:25 UTC, clintoncwolfe commented on test/integration/default/build/s3.tf
> +  bucket        = "aws-demo-s3-bucket-${random_id.bucket_id.hex}"
The intent behind terraform.env (which is the workspace name, or `ENV['INSPEC_TERRAFORM_ENV']` from the Rakefile) is that it be somewhat unique but predicatable; I use cwolfe-01, cwolfe-02, etc.

2018-01-16 22:35 UTC, closed without merging