Add rake task to clean up integration test instances
chef/inspec-aws pull request #17
Opened 2017-02-16 20:31 UTC by vix633

Making the default integration test target cleanup before and after.

2017-02-20 10:14 UTC, chris-rock reviewed
@vix633 Thank you. Thank looks great. I added a suggestion for rake task naming.

2017-02-22 00:00 UTC, Rugbyte approved these changes

2017-02-22 12:35 UTC, chris-redekop approved these changes

2017-02-22 15:29 UTC, JeffreyLyonsD2L approved these changes

2017-02-22 21:58 UTC, AlexBedley requested changes

2017-02-23 17:58 UTC, AlexBedley approved these changes

2017-02-27 14:17 UTC, chris-rock approved these changes
This is a great improvement @vix633 @chris-redekop

2017-02-27 14:18 UTC, merged