Implement aws_iam_user resource
chef/inspec-aws pull request #19
Opened 2017-02-22 21:24 UTC by Stiffni

Fixes #6 

- [x] squash and rebase after code review

2017-02-23 14:39 UTC, chris-rock requested changes

2017-02-23 15:54 UTC, chris-redekop requested changes

2017-03-08 17:22 UTC, chris-redekop requested changes

2017-03-08 21:55 UTC, AlexBedley approved these changes

2017-03-08 22:02 UTC, chris-redekop approved these changes

2017-03-09 14:53 UTC, JeffreyLyonsD2L approved these changes

2017-03-09 16:04 UTC, Rugbyte approved these changes

2017-03-16 15:05 UTC, vix633 approved these changes

2017-03-16 15:09 UTC, chris-rock approved these changes
Thank you all! Great work.

2017-03-16 15:09 UTC, merged