skeletal aws_iam_policys
chef/inspec-aws pull request #193
Opened 2018-01-19 06:15 UTC by rx294

2018-01-26 22:09 UTC, clintoncwolfe requested changes
Looks good - just a couple of docs changes.  Thanks for another excellent contribution!

2018-01-26 22:09 UTC, clintoncwolfe commented on docs/resources/aws_iam_policys.md
> +To test properties of all managed policies that are available in your AWS account, including your own customer-defined managed policies and all AWS managed policies.
Please prefix with "It may be used to test...." to form a complete sentence.

2018-01-26 22:25 UTC, rx294 commented
ah my bad....i have made the corrections thanks @clintoncwolfe

2018-02-01 03:44 UTC, clintoncwolfe approved these changes

2018-02-01 03:45 UTC, merged

2018-02-01 03:48 UTC, rx294 commented
Thank you Clinton!