Issue Fix 197
chef/inspec-aws pull request #198
Opened 2018-01-19 22:47 UTC by rx294

2018-01-19 22:49 UTC, adamleff commented
Please use more descriptive PR titles and always include a description. A user should not have to refer to another issue in order to determine the scope and intention of a pull request. Thank you!

2018-01-19 23:15 UTC, rx294 commented
Thank you @adamleff I have made the changes.

2018-01-23 06:05 UTC, clintoncwolfe requested changes
Just a couple of docs changes - looks good.  I've run unit and integration tests, both pass fine.

2018-01-23 13:39 UTC, rx294 commented on docs/resources/aws_iam_root_user.md
>  ### Test that the AWS root account has only one access key
Ah..sorry meant to say at-least...

2018-01-23 13:39 UTC, rx294 commented on docs/resources/aws_iam_root_user.md
> +The `have_access_keys` matcher tests if the AWS root user has at least one access key.
another oops!

2018-01-23 13:43 UTC, rx294 commented
Thanks for the review @clintoncwolfe ...I have made the corrections...apparently I suck at documentation 😆

2018-01-23 16:00 UTC, clintoncwolfe approved these changes

2018-01-23 16:01 UTC, merged

2018-01-23 16:02 UTC, clintoncwolfe commented
Thanks again - great contribution!

2018-01-23 18:57 UTC, rx294 commented
Thank you for the approval!