[ISSUE-24] - Use terraform environment to avoid integration tests collisions
chef/inspec-aws pull request #35
Opened 2017-04-30 00:08 UTC by mtjandra

## Summary - Addresses https://github.com/chef/inspec-aws/issues/24
* When running integration tests, use Terraform environment based on environment variable `INSPEC_TERRAFORM_ENV` to avoid collisions
  * If `INSPEC_TERRAFORM_ENV` is not set, a random string will be used
  * I chose not to default to `AWS_SECRET_ACCESS_KEY` if in the future we have parallel integration tests running in Travis
* Use Terraform environment as a namespace for AWS artifacts
* Use attribute file so that Inspec is  aware of the Terraform environment used
* Added additional integration test to cover case where we test by EC2 ID

Signed-off-by: Miles Tjandrawidjaja <miles@tjandrawidjaja.com>

2017-04-30 20:17 UTC, chris-redekop requested changes
Welcome to the project and thanks for the fix, Miles!  This looks good to me, overall.  I have a couple of questions/requests.

2017-05-04 15:20 UTC, Rugbyte approved these changes

2017-05-04 15:54 UTC, chris-redekop approved these changes

2017-05-04 18:20 UTC, AlexBedley approved these changes

2017-05-05 14:22 UTC, chris-rock requested changes
@mtjandra Could you rebase this on latest master?

2017-05-22 23:27 UTC, chris-rock approved these changes
This is a great addition. Thank you @mtjandra

2017-05-22 23:27 UTC, merged