Add list_users
chef/inspec-aws pull request #45
Opened 2017-05-10 19:48 UTC by Stiffni

We messed up the other branch for #34, so we made a new branch with the same changes.
Ready to merge pending final approval.

2017-05-11 13:53 UTC, chris-redekop requested changes
I have a concern about the **convert** method.

2017-05-11 15:28 UTC, chris-redekop approved these changes

2017-05-11 15:54 UTC, AlexBedley approved these changes

2017-05-12 17:39 UTC, vix633 approved these changes

2017-05-18 18:03 UTC, Rugbyte approved these changes

2017-05-22 23:32 UTC, chris-rock approved these changes
Thank you @Stiffni for this addition!

2017-05-22 23:32 UTC, merged