[ISSUE-36] - Cover Recommendation 1.10
chef/inspec-aws pull request #47
Opened 2017-05-14 01:20 UTC by mtjandra

## Summary - Addresses https://github.com/chef/inspec-aws/issues/36
* Covers recommendation 1.10
* I do not know if we should cover this in an integration test, since it doesn't seem Terraform has a revert strategy. **Looking for advice**.

Sample Tests
```
describe aws_iam_password_policy do
  its('prevent_password_reuse?') { should be true }
end

describe aws_iam_password_policy do
  its('number_of_passwords_to_remember') { should eq 1 }
end
```

Sample Failure Output (Manually Tested)
```
aws_iam_password_policy prevent_password_reuse?
   ∅  should equal true
     
   expected true
       got false
     
aws_iam_password_policy number_of_passwords_to_remember
   ∅  this policy does not prevent password reuse

```

Sample Success Output (Manually Tested)
```

  aws_iam_password_policy prevent_password_reuse?
     ✔  should equal true
  aws_iam_password_policy number_of_passwords_to_remember
     ✔  should eq 1
```

2017-05-21 15:33 UTC, chris-redekop requested changes
Looks good.  Just the one name change.

2017-05-21 15:40 UTC, chris-redekop approved these changes

2017-05-25 19:26 UTC, vix633 approved these changes

2017-05-30 15:31 UTC, chris-redekop commented
Please rebase this branch to master.

2017-05-30 20:15 UTC, aduric approved these changes

2017-05-30 23:04 UTC, mtjandra commented
> Please rebase this branch to master.

Rebased

2017-05-30 23:26 UTC, chris-redekop commented
@AlexBedley any more comments/requests on this one?

2017-05-31 14:37 UTC, AlexBedley approved these changes

2017-05-31 18:16 UTC, chris-redekop commented
@chris-rock, this one is ready for your final review/merge.

2017-06-13 05:41 UTC, chris-rock commented
@mtjandra great improvement. I'd like to see integration tests, too. Can you please open an issue for that, so that we can discuss how we can solve the issues you mentioned above?

2017-06-13 05:41 UTC, merged

2017-06-13 23:36 UTC, mtjandra commented
@chris-rock  issue https://github.com/chef/inspec-aws/issues/59 added