[ISSUE-39] - Cover Recommendation 1.12
chef/inspec-aws pull request #49
Opened 2017-05-14 03:30 UTC by mtjandra

## Summary - Addresses https://github.com/chef/inspec-aws/issues/39
* Adding resource aws_iam_root_user
* Not sure if an integration test should be added, since it is unlikley we will use a root account to setup a test environment. **Looking for advice here**

Sample Test
```
describe aws_iam_root_user do
  its('access_key_count') { should eq 0 }
end
```

Sample Output
```
AWS Root-User
   ✔  access_key_count should eq 0
```

2017-05-18 13:09 UTC, chris-redekop approved these changes
We'll need to add a couple more reviewers here first.  We can discuss at standup.

2017-05-19 10:04 UTC, chris-redekop requested changes
Please add a **to_s** method to this class, which controls how it appears in InSpec test reports.  (You can run the integration tests to see the effect.)

See https://github.com/chef/inspec-aws/pull/33#discussion_r113677230 for background.

2017-05-19 15:17 UTC, AlexBedley approved these changes

2017-05-23 15:05 UTC, AlexBedley commented on libraries/aws_iam_root_user.rb
> +    summary_account['AccountAccessKeysPresent']
Nice investigation. For some reason I thought ruby hashes were indifferent to string vs symbol and treated them as equal. good to know I'm wrong

2017-05-24 18:26 UTC, chris-redekop requested changes

2017-05-24 18:26 UTC, chris-redekop commented on libraries/aws_iam_root_user.rb
> +  def to_s
Would you please include the output of a test run with this implementation?

2017-05-24 22:43 UTC, mtjandra commented on libraries/aws_iam_root_user.rb
> +  def to_s
Sure thing it looks like this:
```
  IAM Root
     ✔  User access_key_count should eq 0
```

For whatever reasons only the top two words appear on the first line, then the rest appears on the next. Here is more evidence if you were to just name it `1 2 3`, and  have two tests.
```
  1 2
     ✔  3 access_key_count should eq 0
     ✔  3 access_key_count should eq 0
```

This is something that we can investigate further if it isn't how you pictured the formatting.

2017-05-25 17:11 UTC, chris-redekop commented on libraries/aws_iam_root_user.rb
> +  def to_s
My observation is that it's space-delimited like so "<category><class> <instance>".  So maybe "AWS Root-User <numeric aws account ID>"?  Account ID is not a dealbreaker, just an idea.  How easy would it be to retrieve?

2017-05-25 19:37 UTC, mtjandra commented on libraries/aws_iam_root_user.rb
> +  def to_s
Yeah I'm happy to change it. Usually where there is a lack of guidelines I like having something that looks not quite right, so it prompts consistency. What is your suggestion, I am thrown off by the "Account ID" comment.

1. AWS Root-User
2. Root-User <AccountID>

2017-05-30 00:24 UTC, mtjandra commented on libraries/aws_iam_root_user.rb
> +  def to_s
Updated. Output is now:
```
 IAM Root-User
     ✔  access_key_count should eq 0
```

If you are interested in adding the account ID have a look at https://github.com/chef/inspec-aws/pull/54

2017-05-30 02:05 UTC, chris-redekop approved these changes
Looks good!

2017-05-30 13:21 UTC, Stiffni approved these changes

2017-05-30 23:27 UTC, chris-redekop commented
Please rebase this branch, then we'll send it off for final review.

2017-05-30 23:40 UTC, mtjandra commented
> Please rebase this branch, then we'll send it off for final review.

So we rebase before merge, but we don't rebase on merge. Is this intentional? If I look at the git history I see a lot of commits marked as  `Merged pull request #xx abcdefg`. This is similar to running `git merge mybranch --no-ff`.

2017-05-31 18:16 UTC, chris-redekop commented
@mtjandra and I discussed rebasing offline.  This is a Chef convention.  Thanks, @mtjandra , for rebasing!

@chris-rock , this one is ready for your final review/merge.

2017-06-13 05:44 UTC, chris-rock approved these changes
Thank you @mtjandra Same as the other PR, lets find out how we can write integration tests for this resource too

2017-06-13 05:44 UTC, merged

2017-06-13 23:33 UTC, mtjandra commented
@chris-rock  Issue https://github.com/chef/inspec-aws/issues/58 added