[ISSUE-52] - Remove Random Namespace
chef/inspec-aws pull request #57
Opened 2017-06-07 02:42 UTC by mtjandra

* Addresses https://github.com/chef/inspec-aws/issues/52
* Sample output (beginning and end) of running `bundle exec rake test:integration`
```
[inspec-aws (master)]> bundle exec rake test:integration
Please enter a namespace for your integration tests to run in: PullRequestDemo
----> Creating terraform environment
cd /home/mtjandra/code/inspec-aws/test/integration/build/ && terraform env new PullRequestDemo
Created and switched to environment "PullRequestDemo"!

You're now on a new, empty environment. Environments isolate their state,
so if you run "terraform plan" Terraform will not see any existing state
for this configuration.

...

Destroy complete! Resources: 3 destroyed.
----> Destroying terraform environment
cd /home/mtjandra/code/inspec-aws/test/integration/build/ && terraform env select default
Switched to environment "default"!
cd /home/mtjandra/code/inspec-aws/test/integration/build && terraform env delete PullRequestDemo
Deleted environment "PullRequestDemo"!
```

* Example of running individual tasks that now take parameters
```
[inspec-aws (master)]> bundle exec rake test:configure_test_environment[SingleTask]
----> Creating terraform environment
cd /home/mtjandra/code/inspec-aws/test/integration/build/ && terraform env new SingleTask
Created and switched to environment "SingleTask"!

You're now on a new, empty environment. Environments isolate their state,
so if you run "terraform plan" Terraform will not see any existing state
for this configuration.
[inspec-aws (master)]> bundle exec rake test:destroy_test_environment[SingleTask]
----> Destroying terraform environment
cd /home/mtjandra/code/inspec-aws/test/integration/build/ && terraform env select default
Switched to environment "default"!
cd /home/mtjandra/code/inspec-aws/test/integration/build && terraform env delete SingleTask
Deleted environment "SingleTask"!
```

2017-06-07 18:08 UTC, Rugbyte approved these changes

2017-06-07 18:15 UTC, chris-redekop approved these changes

2017-06-07 18:15 UTC, chris-redekop commented on Rakefile
> +  task :destroy_test_environment, :namespace do |t, args|
This looks good.  I confirmed that I can call the **configure** and **destroy** tasks individually with the argument:

```
ubuntu@ubuntu-xenial:~/inspec-aws$ bundle exec rake test:destroy_test_environment[cr-foo]
----> Destroying terraform environment
cd /home/ubuntu/inspec-aws/test/integration/build/ && terraform env select default
Switched to environment "default"!
cd /home/ubuntu/inspec-aws/test/integration/build && terraform env delete cr-foo
Deleted environment "cr-foo"!
```

2017-06-13 05:52 UTC, chris-rock commented
I agree that we want to add a meaning to the namespace, but wouldn't it be better to prefix with a fixed name and use a random number then?

2017-06-13 23:42 UTC, mtjandra commented
> I agree that we want to add a meaning to the namespace, but wouldn't it be better to prefix with a fixed name and use a random number then?

I believe we want to catch and fail on namespace conflicts, as this would suggest that the resources created from a previous Terraform run was not cleaned up correctly. Ideally we would want to catch these conflicting namespaces across all test runs, but the best we can do is detect conflicts based on some particular computer (terraform environments are not known to AWS).

2017-06-14 12:03 UTC, chris-redekop commented
Yes, using a (partially) random ID to avoid env collisions will mask teardown issues from ANY previous runs.  I want to call this out as an anti-feature: the teardown failed for some reason, so we want to investigate and cleanup.  (Our experience has been that when teardown fails, resources are left with their AWS-cost meter running; and without an out-of-band process to clean these up, they and their costs just accumulate.)  For this reason, I propose that we don't mask collisions with a (partially) random ID.

OTOH, if you need to run multiple concurrent test setups, it's easy to manually tack on an incrementing integer to your env ID; so the lack of a (partially) random ID shouldn't be a blocker.

This would make doing the right thing--make sure your test resources are cleaned up--easier and doing the wrong thing--ignoring collisions with previous runs--harder.

What do you think, @chris-rock ?

2017-06-14 14:28 UTC, aduric approved these changes

2017-06-14 17:33 UTC, vix633 approved these changes

2017-06-21 17:16 UTC, chris-rock requested changes
While I understand your need and we should find a solution for this, I hesitate to approve a integration test that requires human interaction. There needs to be a path to use this in CI/CD environments. So how would I set the values in a CI environment that spins up terraform?

2017-06-21 18:23 UTC, chris-redekop commented
Thanks, @chris-rock .  As discussed, an environment variable is a good approach here: if it exists, use its value as the Terraform env name; otherwise, prompt the user for a Terraform env name.

When I discussed with @mtjandra , he informed me that the tests already behave like this: they look for an environment variable named **INSPEC_TERRAFORM_ENV**.

I confirmed that this works as desired (no prompt!):

```bash
ubuntu@ubuntu-xenial:~/inspec-aws$ INSPEC_TERRAFORM_ENV=cr2 bundle exec rake test:integration
cd /home/ubuntu/inspec-aws/test/integration/build/ && terraform env new cr2
Created and switched to environment "cr2"!

You're now on a new, empty environment. Environments isolate their state,
so if you run "terraform plan" Terraform will not see any existing state
for this configuration.
----> Cleanup
cd /home/ubuntu/inspec-aws/test/integration/build/ && terraform destroy -force

Destroy complete! Resources: 0 destroyed.
----> Setup
cd /home/ubuntu/inspec-aws/test/integration/build/ && terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
``` 
Is this what you meant, @chris-rock ?  If so, would you like to see any other changes here, or are we good to go?

2017-06-28 12:48 UTC, chris-rock commented on Rakefile
> +    namespace = ENV['INSPEC_TERRAFORM_ENV'] || prompt("Please enter a namespace for your integration tests to run in: ")
Lets add documentation for that in our readme

2017-06-28 12:53 UTC, chris-redekop commented on Rakefile
> +    namespace = ENV['INSPEC_TERRAFORM_ENV'] || prompt("Please enter a namespace for your integration tests to run in: ")
This made it into our README from the original "create separate env" issue.  Done!

2017-06-28 12:54 UTC, chris-rock commented on Rakefile
> +    namespace = ENV['INSPEC_TERRAFORM_ENV'] || prompt("Please enter a namespace for your integration tests to run in: ")
Perfect, Thank you for double-checking

2017-06-28 12:54 UTC, chris-rock approved these changes
Nice improvement @mtjandra

2017-06-28 12:55 UTC, merged