Fix circular-reference warning
chef/inspec-aws pull request #70
Opened 2017-07-05 18:20 UTC by chris-redekop

2017-07-14 16:53 UTC, Stiffni approved these changes

2017-07-19 20:20 UTC, aduric commented on test/unit/resources/aws_iam_password_policy_test.rb
> +  def configure_policy_password_reuse_prevention(value:, n: 1)
This seems weird. Is this canonical Ruby to have a key param without a value? Maybe we should be passing `value` as a required param.

2017-07-19 20:21 UTC, aduric requested changes
See inline comments.

2017-07-19 21:02 UTC, chris-redekop commented
Thanks for catching the merge conflict, @aduric .  Before starting the rebase, I checked for the problem in master, and it's no longer there!  I will close this PR and its issue.

2017-07-19 21:02 UTC, closed without merging