A real-world working AwsIamUsers
chef/inspec-aws pull request #71
Opened 2017-07-06 20:21 UTC by chris-redekop

This is the rebase of our long-live aws-users branch.  It works!

2017-07-06 20:21 UTC, chris-redekop commented on libraries/aws_iam_user.rb
> +    "IAM User #{@user[:name]}"
Updated to use the provider's output.

2017-07-06 20:22 UTC, chris-redekop commented on libraries/aws_iam_user_provider.rb
> +      def name(aws_user)
Added for *aws_iam_user#to_s*.

2017-07-06 20:23 UTC, chris-redekop commented on test/integration/verify/controls/aws_iam_users.rb
> +describe aws_iam_users.where(has_console_password?: true).where(has_mfa_enabled?: false) do
Our new users integration test!

2017-07-06 20:23 UTC, chris-redekop commented on libraries/aws_iam_user.rb
> +    describe aws_iam_user(name: 'test_user_name') do
**aws_iam_user** now takes a hash of options.

2017-07-06 20:24 UTC, chris-redekop commented on libraries/aws_iam_users.rb
> +        .add(:exists?) { |x| !x.entries.empty? }
This is where we can add methods to the user-collection as a whole.  Exists struck me as immediately useful, but we might need to add more as we go...

2017-07-06 20:25 UTC, chris-redekop commented on test/integration/verify/controls/aws_iam_user.rb
> +describe aws_iam_user(name: mfa_not_enabled_user) do
Updated for **aws_iam_user's** new hash of options.

2017-07-06 20:25 UTC, chris-redekop commented on test/unit/resources/aws_iam_user_test.rb
> +    assert(
Yes, RuboCop!

2017-07-06 22:16 UTC, Rugbyte approved these changes

2017-07-20 15:58 UTC, aduric approved these changes

2017-07-20 20:22 UTC, Stiffni approved these changes

2017-07-27 15:22 UTC, chris-rock requested changes
@chris-redekop Thank you for your great improvement. I just added a minor feedback. LGTM then.

2017-07-27 15:22 UTC, chris-rock commented on libraries/aws_iam_user.rb
> +    "IAM User #{@user[:name]}"
Can we introduce a method like `name` that reads out the user name? This would allow anybody to access the value for a test too

2017-07-27 15:22 UTC, chris-rock commented on libraries/aws_iam_users.rb
> +  example ''
We should add an example that uses exists

2017-07-27 15:22 UTC, chris-rock commented on libraries/aws_iam_users.rb
> +        .add(:exists?) { |x| !x.entries.empty? }
Makes sense to add more values going forward 👍

2017-07-30 11:22 UTC, totem-user commented on libraries/aws_iam_user.rb
> +    "IAM User #{@user[:name]}"
Sure thing.  Name addded.

2017-07-30 11:22 UTC, totem-user commented on libraries/aws_iam_users.rb
> +  example ''
Thanks for the reminder.  I added a couple of examples.

2017-07-30 11:23 UTC, chris-redekop commented on libraries/aws_iam_user.rb
> +    "IAM User #{@user[:name]}"
Sure thing.  Name added.

2017-07-30 11:24 UTC, chris-redekop commented on libraries/aws_iam_users.rb
> +  example ''
Thanks for the reminder.  Examples added.

2017-08-08 13:50 UTC, chris-rock approved these changes
Thank you @chris-redekop

2017-08-08 13:50 UTC, merged